ARG BASE_IMAGE_VERSION
FROM geonode/geoserver:${BASE_IMAGE_VERSION}

# COPY ./entrypoint.sh /usr/local/tomcat/tmp
# RUN chmod +x /usr/local/tomcat/tmp/entrypoint.sh

# CMD ["/usr/local/tomcat/tmp/entrypoint.sh"]
